import{test, expect} from '@playwright/test';
test('Codegen Script', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/client/#/auth/login');
  await page.getByRole('textbox', { name: 'email@example.com' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('goneliw313@jobraux.com');
  await page.getByRole('textbox', { name: 'enter your passsword' }).click();
  await page.getByRole('textbox', { name: 'enter your passsword' }).fill('Sampathkumar@1');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: ' Add To Cart' }).nth(1).click();
  await page.getByRole('button', { name: ' Add To Cart' }).first().click();
  await page.getByRole('button', { name: ' Add To Cart' }).nth(2).click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: 'Checkout❯' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('000');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Sampath');
  await page.getByRole('textbox', { name: 'Select Country' }).click();
  await page.getByRole('textbox', { name: 'Select Country' }).fill('indi');
  await page.getByRole('button', { name: 'India' }).click();
  await page.getByText('Place Order').click();
  await expect(page.getByRole('heading', { name: 'Thankyou for the order.' })).toBeVisible();
  await expect(page.locator('#htmlData')).toContainText('| 6a9348fe21054ba465fcd0f9 |');
  await page.getByRole('button', { name: '   ORDERS' }).click();
  await page.getByRole('button', { name: 'View' }).nth(2).click();
  await expect(page.getByText('6a9348fe21054ba465fcd0f9')).toBeVisible();
  await page.getByRole('button', { name: 'Sign Out' }).click();
});